export const TUTORIAL_STORAGE_KEY = "rivals-vod-review-tutorial-complete";

export const tutorialSteps = [
  {
    id: "new-review",
    target: "new-review",
    title: "Start a review",
    body: "Create a new review from here. This opens the setup wizard where the reviewer chooses the source, hero, and template.",
    placement: "bottom",
    spotlightOffsetY: -2,
  },
  {
    id: "wizard-source",
    target: "wizard-source",
    title: "Choose the source",
    body: "Start blank or paste a Discord review. JSON import is intentionally disabled until the bot workflow is ready.",
    placement: "right",
  },
  {
    id: "wizard-template",
    target: "wizard-template",
    title: "Pick hero and template",
    body: "Select the hero and template style. Page 2 and onward will automatically use the matching continuation template when it exists.",
    placement: "right",
  },
  {
    id: "wizard-text",
    target: "wizard-text",
    title: "Add review text",
    body: "Paste the review text or add starter notes. The editor can turn pasted review text into reusable segments.",
    placement: "left",
  },
  {
    id: "segments",
    target: "segments-panel",
    title: "Use text segments",
    body: "Segments live here. Select one, then click the canvas to place it, or auto-place all detected segments.",
    placement: "right",
  },
  {
    id: "canvas",
    target: "review-canvas",
    title: "Edit on the canvas",
    body: "Drag, resize, rotate, group, and double-click text layers to edit them. Free text can be appended into an existing segment or turned into a new segment from the text editor.",
    placement: "left",
  },
  {
    id: "comparison",
    target: "comparison-tool",
    title: "Add comparisons",
    badge: "New",
    body: "Use Comparison for side-by-side coaching blocks such as Good versus Not optimal or Do this versus Not this. Each block can include images, labels, captions, and a takeaway.",
    placement: "bottom",
  },
  {
    id: "wcag",
    target: "wcag-tool",
    title: "Check contrast",
    badge: "New",
    body: "Use WCAG when styling text or shapes. Good contrast keeps reviews readable across templates and helps make the document accessible instead of only looking right on one background.",
    placement: "bottom",
  },
  {
    id: "full-text-width",
    target: "full-text-width",
    title: "Choose text width",
    badge: "New",
    body: "Use this switch when text should span the page instead of reserving space for the screenshots safe zone.",
    placement: "left",
  },
  {
    id: "layers",
    target: "layer-list",
    title: "Manage layers",
    body: "Use the layer list to hide, lock, group, rename, reorder, and select nested folders like a design tool.",
    placement: "left",
  },
  {
    id: "history",
    target: "history-panel",
    title: "Review history",
    badge: "New",
    body: "Use History to inspect recent edits and jump back to an earlier state when you need a faster way to backtrack than repeated undo.",
    placement: "left",
  },
  {
    id: "export",
    target: "export-actions",
    title: "Export or print",
    body: "Export PNGs for the active page or use Print for all pages. If you use Print make sure to enable 'background graphics' and select 'Save as PDF' in the Destination selection.",
    placement: "bottom",
    spotlightOffsetY: -2,
  },
  {
    id: "example",
    target: "view-example",
    title: "View an example",
    body: "Open the example review here whenever you want a reference to what a completed review might look like.",
    placement: "right",
  },
];
